wifi:
  networks:
  # - ssid: "Mickey"
  #   password: !secret wifi_pw_zak
  - ssid: "GoonNet"
    password: !secret wifi_pw

  # manual_ip:
  #   static_ip: 192.168.69.${ipnum}
  #   gateway: 192.168.1.1
  #   subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Fallback ${friendly_name}"
    password: "mickensfallback"

captive_portal:

api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_enc_key

logger:

ota:

