name: "clean-actions"
concurrency: "clean-actions"
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  "clean-actions":
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      # this one checks out the default branch at first
    - name: setup
      uses: ./.github/actions/setup/
      with:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: clean-actions
      env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
      run: nix develop '.#ci' -c .github/clean-actions.nu
