name: "nixcfg-clean"
concurrency: "nixcfg-clean"
on:
  schedule:
    - cron: '0/20 * * * *'
  workflow_dispatch:
jobs:
  "clean":
    runs-on: "ubuntu-latest"
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-substituters = https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org
          extra-trusted-public-keys = nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4=
    - name: clean
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        nix develop .#ci -c ./ci/clean.nu
