on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@colemickens/expose-runs-on
    permissions:
      id-token: "write"
      contents: "read"
    with:
      runs-on: "raisin-default"
      runner-map: |
        {
          "aarch64-linux": "rock5b-default",
          "x86_64-linux": "raisin-default"
        }
