name: "nixcfg-next"
concurrency: "nixcfg-next"
on:
  schedule:
    - cron: '0/20 * * * *'
  workflow_dispatch:
    inputs:
      activate:
        default: false
        required: true
        type: boolean
  push:
    branches:
      - "main"
jobs:
  "update":
    runs-on: "raisin-default"
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: next
      run: |
        nix develop .#ci -c ./ci-next.nu update
  "deploy":
    strategy:
      fail-fast: false
      matrix:
        host:
          - name: "raisin"
          - name: "xeep"
          - name: "rock5b"
          - name: "radxazero1"
          - name: "openstick"
          - name: "slynux"
          - name: "h96maxv58"
    runs-on: "raisin-deployer"
    needs: [ "update" ]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: main-next
    - name: deploy-${{matrix.host.name}}
      run: |
        timeout 600 \
          nix develop .#ci -c ./ci-next.nu deploy --activate=${{ github.events.inputs.activate }} ${{matrix.host.name}}
